// Generated by LiveScript 1.2.0
var gulp, plugins, $;
gulp = require('gulp');
plugins = require('gulp-load-plugins');
$ = plugins();
gulp.task('style', function(){
  return gulp.src('./assert/css/main.styl').pipe($.plumber()).pipe($.stylus()).pipe(gulp.dest('./assert/css'));
});
gulp.task('script', function(){
  return gulp.src('./assert/js/main.ls').pipe($.plumber()).pipe($.livescript()).pipe(gulp.dest('./assert/js'));
});
gulp.task('watch', ['style', 'script'], function(){
  gulp.watch('./assert/css/*.styl', ['style']);
  return gulp.watch('./assert/js/*.ls', ['script']);
});